apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f quip-pathdb.yml.PRISM -o openshift2
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: iip
  name: iip
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: iip
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f quip-pathdb.yml.PRISM -o openshift2
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: iip
    spec:
      containers:
      - image: docker-registry.default.svc:5000/pathdb/iip:latest
        imagePullPolicy: ""
        name: ca-iip
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - mountPath: /data/images
          name: data
          subPath: 'pathdb/files/wsi'
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
