apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f quip-pathdb.yml.PRISM -o openshift2
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: segloader
  name: segloader
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: segloader
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f quip-pathdb.yml.PRISM -o openshift2
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: segloader
    spec:
      containers:
      - image: docker-registry.default.svc:5000/pathdb/segloader:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        imagePullPolicy: ""
        name: quip-segloader
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
